Yoast/Yoast-SEO-for-TYPO3

Classes/Backend/PageLayoutHeader.php
Configuration/TypoScript/setup.txt
Resources/Public/JavaScript/bundle.js
Resources/Public/JavaScript/plugin.js
ext_localconf.php

Content for the analyzer and snippet preview is rendered through a special page type in FE context. This ensures that no template related content interferes and we still benefit from the complete FE context when it comes to rendering content elements.
This fixes both #5 and #6 because the URL returned is created only by invoking `typolink` and `<img />` tags are rendered as needed by the appropriate Core methods.

Frontend preview using FE page with specific type

---

Classes/Backend/PageLayoutHeader.php
Configuration/TCA/Overrides/pages_language_overlay.php
Resources/Public/JavaScript/bundle.js
Resources/Public/JavaScript/plugin.js
ext_tables.sql

Besides just making the focus keyword property available for an overlay this fixes the preview loaded for analyzing. The ID and sys_language are determined using the PageLayoutController and as such the selected language in the editor is respected. 
The editing functionality of the snippet preview is also modified due to this localization thingy, metadata for a specific translation must be stored in a separate table, so the callback respects the `recordtable` directive.

#10 page overlay focuskeyword

---

Configuration/TypoScript/setup.txt
Resources/Public/JavaScript/bundle.js
Resources/Public/JavaScript/plugin.js

The used locale is resolved from `config.locale_all`, the value can be modified from TypoScript and the integrator of the site is encouraged to do so properly.
Since there's no reliable method to resolve the used locale for the current page the value is rendered along with the preview XML.

Provide the configured locale with the FE preview XML

---

Classes/Backend/PageLayoutHeader.php
Resources/Public/JavaScript/bundle.js
Resources/Public/JavaScript/plugin.js
ext_localconf.php

Respect the user setting `lang` when loading the YoastSEO app. Use a static mapping from language keys used by TYPO3 to locales used for YoastSEO translation files.

Resolve translations JSON based on the language set by the user

---

Classes/Backend/PageLayoutHeader.php

When FluidTYPO3/flux is installed Yoast/Yoast-SEO-for-TYPO3 causes PHP error on page module. No idea why...
Fixes: #60

[BUGFIX] Fix incompatibility issue with FluidTYPO3/flux extension #60

---

Classes/Backend/PageLayoutHeader.php

YoastUtility::snippetPreviewEnabled was called with the uid of the page_language_overlay record, instead of uid of page. 
So the wrong typoscript config was used in Backend Module.

[BUGFIX] Disable snippet preview does not work in localized pages

---

Configuration/TCA/Overrides/pages_language_overlay.php

I do not know if it was intentional, but the PageOverlay record (TYPO3 default view) did not have the possibility to edit the SEO title.

[BUGFIX] Missing SEO-Title in Page Overlay

---

Classes/Frontend/PageRenderer/PageMetaRenderer.php
Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/pages_language_overlay.php
Configuration/TypoScript/setup.txt
ext_tables.sql

Don't use default rendering of title tag from TYPO3 when the Yoast plugin is enabled. Also added possibility to disable Yoast in frontend on a specific page

[TASK] Don't use default rendering of title tag from TYPO3

---

ext_localconf.php

Adds the missing entry for `tx_yoastseo_title` in `pageOverlayFields`
fixes #122

[BUGFIX] add missing tx_yoastseo_title from pageOverlayFields

---

Resources/Private/Partials/TwitterCards.html

Twitter cards must use the 'name' attribute in the metatag instead of the 'property' attribute. Otherwise they can not be parsed by twitter, see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

[BUGFIX] Fix syntax for twitter card metatags

---

Resources/Public/JavaScript/Tca.js

* Javascript bugfixes: extra cornerstone check, progressbar bugfix (when the selected tca title field was earlier in the dom than yoast), and multiple duplicated jQuery selectors optimized
* jQuery selected elements have a dollar sign prepended, so it's clear it's a jQuery object
* Creating/editing a record which has Yoast-SEO configuration
Fixes #

TCA Javascript bugfixes and optimization

---

Classes/UserFunctions/SnippetPreview.php

By using cURL with the option to don't verify peer, you will be able
to use the snippet preview on installations with self signed certificates.
Resolves: #222

[BUGFIX] Use cURL to fetch meta tags

---

Classes/Hooks/RealUrlAutoConfiguration.php

* array_merge will be remove all other "fileName"-settings from realurl_autoconfig. This could be unwanted.
After install EXT:yoast_seo 3.0.4 look at the generated RealURL configuration. All settings like "TYPO3_CONF_VARS.EXTCONF.realurl.DOMAIN.fileName.acceptHTMLsuffix" will be gone.
*

Prevent overwrite settings from other RealURL autoconfig hooks

---

Classes/Middleware/PageRequestMiddleware.php
Classes/UserFunctions/SnippetPreview.php
Configuration/RequestMiddlewares.php

* It is now possible to get a valid snippet preview for hidden pages
* The request to the frontend url now has an extra header, which is checked via a Middleware that sets the visibility aspect
* Hide a page in the tree and see if the snippet preview works
Fixes #218

[FEATURE] Enable snippet preview for hidden pages

---

Resources/Public/JavaScript/app.js

* Fix broken HTML markup in modals, caused by TYPO3 security update (TYPO3 v9.5.2)
* Modal.js escapes all content of type string ([see](https://github.com/TYPO3/TYPO3.CMS/commit/c35646c3f7795a4a7b0046a88f146b490fa4883c#diff-4a9e6a863b7911f490c3abb65fb10e01R239)), I therefore wrapped the HTML markup in a new jQuery object.
* Install latest TYPO3 v9
* Check modal before / after PR
Tested the change with TYPO3 v9.5.1 (before security update) and TYPO3 v9.5.4 (after security update). Change also works in TYPO3 v8 (tested v8.7.22) and should therefore be cherry picked in release/3.0 branch.
Fixes #240

[BUGFIX] Fix HTML markup in modals, resolves #240

---

Classes/UserFunc/SitemapXml.php

* Sitemap refactored
* Pages are now collected in the same way CMS9 does it
* Records are now not displayed if the URL is not generated
* For CMS7 compatibility, there is a check if the ConnectionPool exists.
* Having an installation with pages (mountpoints, storage folders etc.) and records (fe. news) and visit the sitemap to see if it all works.
Fixes #233 #230 #228 #215

[BUGFIX] Refactor sitemap for multiple bugfixes

---

Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/pages_language_overlay.php

* Fixed yoast `pages` TCA by providing an integer as default value for `tx_yoastseo_cornerstone`
*  `tx_yoastseo_cornerstone` is stored as an integer in the database, therefore its type shouldn't be `text` (meant for multi line text input)
* If no default value is provided, Typo3 tries to insert an empty string. With a MySQL database running in strict mode, it causes an error and prevents pages to be saved.
* Install Typo3 8.7 with Yoast and a MySQL database in strict mode
* Create a new record of type page

[BUGFIX] Fix TCA to address strict mysql compatibility

---

Classes/DataProviders/PagesWithoutDescriptionOverviewDataProvider.php

* With the release of version 5 (a merge from the CMS8 and CMS9 version), the overview in the backend for pages without meta description was only checking the pages_language_overlay table for CMS8. This fixes it.
* Instead of checking for CMS8 version, I just added an elseif so it only checks if not CMS9.
* Within a CMS8 installation with multiple languages, check if the normal pages (default language) also outputs pages without description.
Fixes #280

[BUGFIX] Fixed PagesWithoutDescription overview for CMS8, only overlay was checked

---

Classes/StructuredData/BreadcrumbStructuredDataProvider.php
Classes/StructuredData/SiteStructuredDataProvider.php

The data used in the structured data providers needs to be cast for further
usage in the methods.
*  Force type casts to avoid type hint errors
* Just add some type casts because the data is delivered as string but expected as integer by the calling methods.
* Install the current master inside TYPO3 9.5.5 with PHP 7.2
* Call the frontend, you should run into a PHP error.
* After applying this patch, you should get the rendered json-ld from the structured data providers
Fixes #264

[BUGFIX] Force type casts to avoid type hint errors

---

Classes/Backend/PageLayoutHeader.php
Classes/Form/Element/SnippetPreview.php
Classes/Utility/YoastUtility.php

* When the base in site configuration is only `/`, the absolute URL was not generated in the backend. This fix always provides a full url.
* When the generated URL has a slash at the first position, the TYPO3_REQUEST_HOST is prepended.
* Set your site base to `/` and see if the snippet preview in the page module and page properties still shows results.
Fixes #279

[BUGFIX] Generate absolute url when the site base is only a slash

---

Documentation/Settings.cfg

Migrated the documentation to the new infrastructure of the docs.typo3.org.
See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html
for more information.

[TASK] Migrated documentation to new infrastructure

---

Classes/Utility/YoastUtility.php

* The EXTCONF and Typoscript settings are now merged, to make sure both ways work (for now)
* I removed the deprecation error/notice because the $allowedDoktypes is never empty. 
* Set custom allowed doktypes in EXTCONF and Typoscript and see if they both work.
Fixes #298

[BUGFIX] Merge EXTCONF and Typoscript settings for allowedDoktypes

---

Classes/StructuredData/BreadcrumbStructuredDataProvider.php

If you have a page at the root level for e.g. some global configuration
the building of the breadcrumb will fail because this site has no site
configuration.
To solve this issue only pages which are inside a site root should be
processed.
* Ignore pages for breadcrumb which are not in a site root
* 
* Create a page (called **Root**) at the top level which is **not** a site root (has no Site Configuration)
* Create on ore multiple pages with Site Configuration **in** the **Root** page
Fixes #

[BUGFIX] Ignore pages for breadcrumb which are not in a site root

---

Classes/Backend/PageLayoutHeader.php

* The page types within the routing configuration can be set as int and as string, since we apply a strict comparison the casting to integer is needed.
* Casting to int on $pageType
* Set the pagetype routing configuration as a string and see if it still works.
Fixes #288

[BUGFIX] Cast the pageType to int within the checkRouteEnhancers to support both int and string routing configuration (#288)

---

Classes/UserFunctions/SnippetPreview.php

* Javascript gets shown in the snippet preview if the javascript is placed after the beginning of the <body> tag. This PR strips out all javascript tags.
* Stripped out all javascript tags with a preg_replace
* Place javascript right in the beginning of the body tag (beware, this bug is only visible if you have no TYPO3SEARCH markers within your body). Then check if the snippet preview shows the javascript, apply this patch and check if the javascript is gone.

[BUGFIX] Strip javascript tags from rendered body

---

Classes/Install/CanonicalFieldUpdate.php
Configuration/TCA/Overrides/pages.php
ext_localconf.php

* With version 5.0, the `canonical_url` field was removed to make room for the core field `canonical_link`. For CMS8, this was not added to the TCA and there was no migration script, this has been added now.
* Added new update script to migrate the old canonical field for both `pages` and `pages_language_overlay`
* Install in CMS8 installation with the old field still available in the database. Perform upgrade wizard script and take a look in the page properties to see if the field is available at the bottom of the "Yoast SEO" tab.
Fixes #312

[BUGFIX] Restored canonical field for CMS8 and added update script to migrate to canonical core field

---

Classes/UserFunctions/SnippetPreview.php

* [BUGFIX] Fixes favicon parsing not working if there are additional attributes after href
* Do match anything except `"` character using `[^"]`, instead of matching anything using `.`
* Previous behaviour: https://regex101.com/r/XTtm2T/1/
* New behaviour: https://regex101.com/r/76230x/1/
Fixes #

[BUGFIX] Fixes favicon parsing not working if there are additional attributes after href

---

CHANGELOG.md
Classes/Install/CanonicalFieldUpdate.php

* Add return true to executeUpdate function in Classes/Install/CanonicalFieldUpdate.php
* Run the CanonicalFieldUpdate Update Wizard from CMS8 to 9 of 10
Fixes #337

[TASK] Add return true to executeUpdate function in CanonicalFieldUpdate.php

---

Classes/Install/CMS8/CanonicalFieldUpdate.php
Classes/Install/CanonicalFieldUpdate.php

* The query used to determine if the canonical field migration is necessary, gives performance issues with larger database. The query has been altered to fix this.
* Instead of the `select('*')` and the `->rowCount()`, the functions `count('uid')` and `->fetchColumn()` are now being used
* Open the upgrade wizard list in the install tool and see if it still shows up (if you have a database which needs migration)

[BUGFIX] Fixed the checkForMigration query within the Canonical update script

---

.ddev/config.yaml
Classes/Service/PreviewService.php

With this change the body text will be cleaned up. `<script>` and `<noscript>` tags will be removed together with the content of the tags. Besides that some whitespaces will be removed.
Resolves: #344

[BUGFIX] Remove script and noscript tags and remove some unneccessary whitespaces

---

Classes/Utility/YoastUtility.php
ext_localconf.php

By this change, no database action is needed anymore while building the TCA and will prevent issues when updating database schemas on empty databases.
* Removed deprecated functionality to provide allowed doktypes in TypoScript. You should configure the doktypes that you want to analyse by setting $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['yoast_seo']['allowedDoktypes']. See the docs for more information.
Before applying the patch: 
* Remove alias field in pages table
* Run db compare
* You will get a failure now
After applying this patch, it will not give an error anymore when a field is missing.
Fixes #350

[!!!][BUGFIX] Removed deprecated functionality to set allowedDoktypes by TypoScript

---

Classes/StructuredData/StructuredDataProviderManager.php

Our MATE extension gathers all set javascript and bundles it. Because there is no closing semicolon for structured data, the next 'var' for example is specified as an unexpected token.
* Bugfix: add closing semi colon for JSON LD data
*
* Check frontend if the semi colon has been added
Fixes #

Add closing semicolon for structured data

---

Classes/ViewHelpers/RecordLinksViewHelper.php

Version 8 does not have the backend modules defined as backend routes. This causes the overview to give an error when there's records present.
Added a version compare to make sure the buildUriFromModule is used in v8 again, as was before.
* Fixed record links viewhelper for version 8
*
* Run a v8 installation and make sure there are records to trigger the error on either the Overview or Redirects (in premium) backend modules
Fixes #

[BUGFIX] use buildUriFromModule for version 8

---

Resources/Private/SCSS/Yoast.scss
Resources/Public/CSS/yoast.min.css

* adapt backend css to prevent overlapping of other third party implementations
* install e.g. the latest t3g/blog version with active PageLayoutHeader (active is default) in the BE.
The score bar is overlapping/overlapped due to it's negative margin-top
Fixes #324

[TASK] Remove negative margin of score bar

---

Classes/Backend/PageLayoutHeader.php
Resources/Public/JavaScript/yoastModal.js
ext_localconf.php

* Make sure the path to the backend CSS is always available to show a modal
Fixes #380

[BUGFIX] Make sure the path to the backend CSS is always available to show a modal

---

Classes/StructuredData/StructuredDataProviderManager.php

When no structured data is available an empty JSON-LD
is embedded into the HTML source:
<script type="application/ld+json">[]</script>
As this is not necessary the patch removes it.

[TASK] Prevent output of empty JSON-LD

---

ext_tables.php

* Removed usage of $_EXTKEY in ext_tables.php causing other extensions to fail
Fixes #383

[BUGFIX] Remove usage of $_EXTKEY in ext_tables.php causing other extensions to fail

---

README.md

* [BUGFIX] Fixed reference to setup.typoscript file
* _none_
* _none_
Fixes #
In README.md a reference to setup.txt has been replaced to setup.typoscript.

[BUGFIX] Fixed reference to setup.typoscript file

---

Classes/Frontend/AdditionalPreviewData.php

* Use the site title as set in the Site Configuration when using TYPO3 v10

[BUGFIX] Use sitetitle of Site configuration when available

---

Classes/Frontend/AdditionalPreviewData.php

Fix issue #392 by checking if `SiteLanguage::getWebsiteTitle()` exists before calling it
* [BUGFIX] Fix TYPO3 v9 support
* Install the extension in TYPO3 v9
Fixes #392

[BUGFIX] Fix TYPO3 v9 support

---

Documentation/Configuration/Sitemap/Index.rst

* Added a warning to the sitemap documentation to only use the functionality in TYPO3 8.7, added a link to the official TYPO3 documentation for the sitemap shipped with EXT:seo
* Added empty lines between the sentences to force a newline.
* The version of the documentation is still on 5.1.0 but this will be fixed with the newest release
* Run `ddev docs` and see if the warning is showed correctly
Fixes #399

[TASK] Updated sitemap documentation with a warning to only use in TYPO3 8.7

---

Classes/Backend/PageLayoutHeader.php
Classes/Controller/ModuleController.php
Classes/Service/PreviewService.php
Classes/Utility/YoastUtility.php
Documentation/Configuration/SnippetPreview/Index.rst
ext_localconf.php

* Basic auth can now be configured, this will be sent with the preview-request
* Disabling the preview is now also possible through global configuration
* Removed old preview configuration (not used anymore)
* Expanded the `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['yoast_seo']` with a new `previewSettings` array
* Set `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['yoast_seo']['previewSettings']['disablePreview'] = true` to check if the preview disappears in the backend
* If you want to test the basic auth with the ddev setup:
* Change the v8 apache configuration within .ddev/apache/apache-site.conf to:
```
<Directory "/var/www/html/v8/">
AllowOverride All
Allow from All
AuthType Basic …
```

[FEATURE] Added global configuration for basic auth and disabling preview

---

Classes/UserFunctions/XmlSitemap.php
Documentation/OtherPlugins/Sitemap/Index.rst

* Detect and render cObjects in TypoScript configuration for Sitemaps
* `$sitemapSettings` is passed as reference, and modified only if keys ending with `.` are found
* Parsing happens before the `table` check, meaning it works for both `pages` and custom records alike.
* Add a cObject to an existing sitemap configuration (or a new one). An example for multilingual handling in `news.additionalWhere` was provided in the documentation
* Check sitemap: only matching records should be displayed
* => The `XmlSitemap` is not covered by unit tests at all. Should I add a test 
Fixes #369

Render cObjects in Sitemap config

---

.github/workflows/ci.yml
composer.json
phpstan.cms11.neon

Added some checks for TYPO3 v11 to the CI process to have an overview if the code is "ready" for TYPO3 v11. This might help getting the extension ready to work with TYPO3 v11. This check might fail and will not prevent any release etc.

Add checks for TYPO3 v11 in CI process

---

Classes/Service/PreviewService.php

* The baseUrl variable was not set correctly, which also meant that the default favicon (/favicon.ico) could not be found on a subpage.
* The uriToCheck is now passed through the parse_url function from which the `$baseUrl` and `$url` variable are set
* Pull branch
* Check if all previews still work
* Check if the favicon (if you have one) is now present on a subpage
Fixes #296

[BUGFIX] Fixed the baseUrl assignment within PreviewService, which also fixes the default favicon call

---

Classes/Service/PreviewService.php

In some cases the ajax request ?route=/ajaxyoast/preview/ results in an empty body in the json response.

[BUGFIX] fixes ajax text analysis returning empty body

---

.github/workflows/ci.yml

The CI was using ubuntu-latest which had only PHP 7.4 - 8.0 support. Switching back to Ubuntu 18 to make sure we can test against older PHP versions as well.

[BUGFIX] Fix issues with CI on older PHP versions

---

Classes/Controller/AjaxController.php
Classes/Service/UrlService.php

* Instead of generating the preview-url and passing through the complete URL as `uriToCheck`, the needed parameters are being send and generating is done within AjaxController
* Url generation is moved, with some small optimizations for `SiteNotFoundException` and removal of `BackendUtility::getPreviewUrl`
* Pull branch
* Check if the preview still works in CMS8, CMS9 and CMS10
* [] I have added unittests to verify the code works as intended

[SECURITY] Move preview url generating to AjaxController, preventing passing complete url as parameter

---

Configuration/TypoScript/Setup/CMS8.typoscript

* `twitter:card` (summary) was not being loaded for CMS8
* Used the same method as the rest of the page meta headers
* Check if the meta tag `twitter:card` is visible in the source with the value `summary`
Fixes #434

[BUGFIX] Render twitter:card in page.meta within CMS8.typoscript

---

Classes/Form/Element/SnippetPreview.php

If for example a news record has set sys_language_uid to value -1 (all languages flag), you won't be able to edit this record anymore.
When yoast_seo/Classes/Service/UrlService.php:75 call TYPO3\CMS\Core\Site\Entity\Site->getLanguageById(-1) it will throw an exception: "Language -1 does not exist on site [SITENAME]."

Preview snippet language fallback for "All [-1]"

---

Classes/Controller/AjaxController.php

* With the latest security fix, the url generation was moved to `AjaxController`. Unfortunately `self::class` was not changed for the `urlToCheck` hook which meant that hooks registered to `UrlService` were not working anymore
* Because it's possible that users have already changed this hook, both `AjaxController` and `UrlService` are valid now.
* First the `AjaxController` hooks are checked with a fallback to `UrlService`
* Add the hook with the steps in the documentation: https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/master/en-us/Configuration/Hooks/Index.html
* Try registering with both `AjaxController` and `UrlService` and see if the hook still works
Fixes #441

[BUGFIX] urlToCheck hook now accepts both AjaxController and UrlService as class (regression)

---

Configuration/TCA/Overrides/pages.php
Documentation/Configuration/OtherPlugins/Index.rst
Documentation/OtherPlugins/Analysis/Index.rst
ext_localconf.php
ext_tables.sql

* Remove DB columns for virtual fields
* Remove legacy `tx_yoastseo_robot_instructions` column definition
I couldn't find any place in the current codebase where data was written in one of those following DB fields:
* `tx_yoastseo_robot_instructions`
* `tx_yoastseo_snippetpreview`
* `tx_yoastseo_focuskeyword_analysis`
* `tx_yoastseo_readability_analysis`
AFAIK they could/should be removed.
* Remove the fields using `./vendor/bin/typo3cms database:updateschema destructive`
* The columns will be prefixed, but everything will keep working:
* Snippet preview
* Overview
* Sitemaps

[CLEANUP] Remove unnecessary DB columns

---

Classes/Service/UrlService.php

Fixes #
This fixes YoastSeoForTypo3\YoastSeo\UserFunctions\SnippetPreview,
the render() function has this line:
$additionalGetVars = urldecode(GeneralUtility::_GET('additionalGetVars'));
And for TYPO3 with version less than 9.5 you are not passing the additionalGetVars,
so the SnippetPreview fails to work with my custom "news" record, which needs a "news" GET param..
Resolves #443 , resolves #266

added additionalGetVars for TYPO3_branch < 9.5

---

composer.json

* We had a dependency of `dev-master` on saschaegerer/phpstan-typo3 which failed now because of the dependency on phpstan/phpstan^1.0
* Because the `slam/phpstan-extensions` package is not yet available for phpstan^1.0, I've set the dependency of phpstan-typo3 to ^0.13 so the builds will succeed again
* If the github actions from this pull request works, it's successful

[TASK] Set saschaegerer/phpstan-typo3 dev-dependency to ^0.13 since slam/phpstan-extensions is not ready for phpstan ^1.0

---

Classes/Form/Element/SnippetPreview.php

This pull request fixes wrong return type in getPreviewPageId().
> TypeError
> Return value of YoastSeoForTypo3\YoastSeo\Form\Element\SnippetPreview::getPreviewPageId() must be of the type int, string returned
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/4ae867e486f6dace18f21c83c33f2627313dfb4a/Classes/Form/Element/SnippetPreview.php#L361
If a `previewPageId` (for example `TCEMAIN.preview.tx_news_domain_model_news.previewPageId = 2`) was provided, a string was returned. With this fix, the value is casted to an integer.

Fix wrong type in getPreviewPageId()

---

Classes/Backend/PageLayoutHeader.php

Error is thrown in page module:
Argument 2 passed to YoastSeoForTypo3\YoastSeo\Backend\AbstractPageLayoutHeader::shouldShowPreview() must be of the type array, null given, called in /var/www/html/public/typo3conf/ext/yoast_seo/Classes/Backend/PageLayoutHeader.php on line 23
This PR can be tested by following these steps (TYPO3 v11.5.2):
* Go into page module
* Select a page in the page tree
* Select "Language" in the upper menu bar (the second select box)
* Select "All languages" in the upper menu bar (the first select box)
$this->getCurrentPage() returns null in this case and $this->shouldShowPreview() expects an array as second argument. The patch avoids this type error, no snippet is displayed in this case.

Fix type error in PageLayoutHeader class

---

composer.json

* Correct branch-alias entry in composer.json
First, this is the correct branch alias. Second, this prevents a composer dependency error when requiring master branch with installed roave/security-advisories, as EXT:yoast_seo is marked as conflict for versions < 7.2.3.

Set branch alias to current version

---

.github/workflows/ci.yml
Classes/Form/Element/SnippetPreview.php
Classes/Service/PreviewService.php
Classes/Service/UrlService.php
Classes/Utility/YoastUtility.php
composer.json
ext_localconf.php

* Introduced PHP8 support for Yoast SEO through composer.json
* Added PHPStan check for TYPO311 with PHP8
* Introduced `RequestFactory` to request the frontend url since `GeneralUtility::getUrl` dropped support for adding headers to the call
* Introduced multiple `??` checks to prevent undefined index warnings
* Removed `pageOverlayFields` from ext_localconf, this functionality was already removed since TYPO3 8
* Fixed 2 bugs regarding `pageTitleField` and `sys_language_uid`
* The check on `sys_language_uid` within the `SnippetPreview` has been expanded to first check if it is an array, otherwise cast to integer because it's not always an array (anymore)
* Test this branch in a PHP8 …

[FEATURE] Support for PHP 8, fixed warnings and introduced RequestFactory for requesting frontend url

---

Classes/Utility/YoastUtility.php

In TYPO11 with PHP 8 there are a `PHP Warning: Undefined array key ...`.
This PR adds a additional check (null coalescing operator's) to prevents this error.

Prevent 'undefined array key' warnings with php 8 when extconf 'allowedDoktypes' missing

---

Documentation/Configuration/StructuredData/Index.rst

Example of getData() return value of a StructuredDataProvider contains incorrect PHP syntax
*
*
*
Fixes #

[DOCS] Fix incorrect PHP array syntax

---

Classes/Service/PreviewService.php

With PHP8.1 the preview doesn't work because of accessing not available offset

[BUGFIX] Fix exception with PHP8.1

---

CHANGELOG.md
ext_tables.php

* See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html, within ext_tables.php there was still a deprecated usage of extension name
* Since we still support CMS9, this was fixed in the same way as the controller calls
* Pull branch and check if the backend modules are still working on CMS9, CMS10 and CMS11
Fixes #474

[BUGFIX] Fixed deprecated extension name usage within ext_tables.php

---

CHANGELOG.md
Classes/Form/Element/FocusKeywordAnalysis.php

* While testing the premium extension with PHP8, an error was found within `FocusKeywordAnalysis.php`
* Added extra checks if the `settings` array exists
* Pull the branch and test in CMS9, CMS10 and CMS11
Fixes #

[BUGFIX] Fixed php8 error within FocusKeywordAnalysis.php

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json

* Github CI failed because of missing `allow-plugins` within composer.json
* Instead of manually setting these in the Github CI yaml files, they're added to the composer.json
* Composer install on the branch, you should not be asked to allow the plugins

[BUGFIX] Fixed Github CI pipelines by adding the correct allow-plugins to composer.json

---

CHANGELOG.md
Classes/Hooks/BackendYoastConfig.php
Resources/Private/Templates/TCA/FocusKeywordAnalysis.html

* Fixes `Content-Security-Policy` issues in the backend of TYPO3 12
* Added extra argument to `addJsInlineCode` within `BackendYoastConfig.php`
* Removed unnecessary/old inline code within `FocusKeywordAnalysis.html`
* Pull branch, enable the content security policy for the backend in 12 and check if there are no errors now
Fixes #533

[BUGFIX] Fixed Content-Security-Policy issues in the backend of TYPO3 12

---

CHANGELOG.md
Classes/StructuredData/BreadcrumbStructuredDataProvider.php

* When the current site language does not exist (probably only in nested sites?), there's a `InvalidArgumentException` being thrown which was not caught.
* Moved the `return (string)$site->.....` within the `try` block and added the `InvalidArgumentException` to be caught
* Pull branch and check if the breadcrumb is still being rendered correctly
Fixes #523

[BUGFIX] Caught InvalidArgumentException within BreadcrumbStructuredDataProvider when the current site language does not exist

---

Configuration/Backend/Modules.php

* fixes wrong access values in the Modules.php, which prevented Yoast groupMods from being available in the Backend user access list. See TYPO3 v12 Documentation for Backend module [access option](https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#confval-access).
*
*
* Login to TYPO3
* Login to TYPO3 Backend
* Select the Backend Users module in the module list
* Select "Backend user groups" in the top menu
* Create a new Backend user group (or use an existing one)
* Select the Access Lists tab
* All Yoast Modules Access List (yoast_YoastSeoDashboard, …

[BUGFIX] Fixe wrong access values in Modules.php

---

Classes/Updates/MigratePremiumFocusKeywords.php

s. https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98024-TCA-option-cruserid-removed.html

[BUGFIX] cruser_id removed on TYPO3 12

---

CHANGELOG.md
Classes/Form/Element/InternalLinkingSuggestion.php
Resources/Private/Language/BackendModule.xlf
Resources/Private/Templates/TCA/InternalLinkingSuggestion.html

* Internal linking suggestions should show a warning within a content element with Language "All" (-1) instead of throwing an exception
* Moved the `getLanguageById(....` call into the `try`/`catch` block to catch the `InvalidArgumentException`, if the `$locale` is `null` the warning is rendered within the template
* Pull branch
* Add a content element with Language "All"
* Check if the warning is shown within the Internal Linking Suggestions
Fixes #543

[BUGFIX] Show warning on linking suggestions when content element is set to 'All Languages' instead of fatal exception

---

CHANGELOG.md
Classes/MetaTag/AdvancedRobotsGenerator.php
Classes/MetaTag/Generator/OpenGraphGenerator.php
Classes/MetaTag/Generator/TwitterGenerator.php
Classes/Record/Record.php

* Metatag generators could throw errors trying to access fields which were not available
* `hasSitemapFields` incorrectly returned `yoastSeoFields` instead of `sitemapFields`
* Added `??` checks to the possibly non-existing fields
* Pull branch
* Test if `setSitemapFields(false)` really does not add the fields in the backend
* Test if the frontend does not throw errors when fields in the database (like `og_image`) do no exist
Fixes #550

[BUGFIX] Added extra checks within the metatag generators in case fields do not exist, fixed hasSitemapFields method with correct property

---

CHANGELOG.md
Classes/Updates/MigratePremiumFocusKeywords.php

* The migration of the premium keywords could not only fail on `cruser_id`, but also when the premium table had other fields which were not present in the new table. This PR filters the array to insert by only allowing columns which are present in the new table.
* Retrieve the columns from the `SchemaManager` and return it as a flipped array from the keys only, to use the `array_intersect_key` on every insert
* Pull branch
* Manually add a column to the old `tx_yoast_seo_premium_focus_keywords` table (and make sure it contains records)
* Run the upgrade wizard and check for errors and if the data has been successfully migrated

[BUGFIX] Filter the columns to import from the old premium database table before inserting in the new table within MigratePremiumFocusKeywords

---

CHANGELOG.md
Classes/Form/Element/InternalLinkingSuggestion.php
Resources/Private/Language/BackendModule.xlf

* In https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/544 an error message was introduced when a content element has "All Language" as the language setting. This PR changes the behavior to use the default language instead, and only show the error when getting the language from the site configuration fails.
* Use `getDefaultLanguage` of `Site` when `sys_language_uid` is `-1`.
* Pull branch
* Set a content element to "All languages"
* Check if the internal linking suggestions are now based on the default language
Fixes #554

[BUGFIX] Fallback to default language within internal linking suggestions if All Languages is selected, changed language error message

---

CHANGELOG.md
Configuration/TCA/tx_yoastseo_prominent_word.php
Resources/Private/Language/TCA.xlf

* Fixed the label of `tx_yoastseo_prominent_word`, wrong declaration within XLF file
* Removed the `exclude=1` of all the fields within the table
* Since the `tx_yoastseo_prominent_word` table already has `hideTable=true` and the table is only used within AJAX requests, no need for exclude fields
* Pull branch
* Check within the Access rights of backend user (groups) if the label is showing and if there are no exclude fields
Fixes #561

[BUGFIX] Fixed wrong label of tx_yoastseo_prominent_word table, removed exclude fields from table

---

CHANGELOG.md
Documentation/Index.rst
Documentation/Introduction/Support/Index.rst

* The documentation still had a mention of Yoast Support with the premium extension, as this extension has been discontinued the support section has been deleted
* On the documentation index there's now a note that the premium extension has been discontinued
Fixes #560

[DOCUMENTATION] Removed mentions of premium extension/support within documentation

---

CHANGELOG.md
Classes/Frontend/AdditionalPreviewData.php

* Defining the website title within the snippet preview previously was only taken from `websiteTitle` of a site's language, now also the global `websiteTitle` is taken into account
* Site attribute is taken from `TYPO3_REQUEST` and the `websiteTitle` is retrieved from `getConfiguration` just like in core
* Pull branch
* Set `websiteTitle` within the site configuration
* Check a (sub) page of the site and start typing in the `seo_title` field, the website title should now stay in place
Fixes #549

[BUGFIX] Use websiteTitle of site configuration for snippet preview

---

CHANGELOG.md
Classes/Service/LinkingSuggestionsService.php

[BUGFIX] Prevent undefined array key warning

---

Classes/Backend/PageLayoutHeader.php
Classes/Controller/AbstractBackendController.php
Classes/EventListener/RecordCanonicalListener.php
Classes/MetaTag/Generator/AbstractGenerator.php
Classes/PageTitle/RecordPageTitleProvider.php
Classes/Utility/JavascriptUtility.php

* Avoid PHP 8.4 deprecations
Fix the following deprecation messages when running `typo3 cache:flush` on console:
PHP Deprecated:  YoastSeoForTypo3\YoastSeo\Backend\PageLayoutHeader::render(): Implicitly marking parameter $params as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/yoast-seo-for-typo3/yoast_seo/Classes/Backend/PageLayoutHeader.php on line 27
PHP Deprecated:  YoastSeoForTypo3\YoastSeo\Controller\AbstractBackendController::returnResponse(): Implicitly marking parameter $moduleTemplate as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/yoast-seo-for-typo3/yoast_seo/Classes/Controller/AbstractBackendController.php on line 25 …

Avoid PHP 8.4 deprecations

---

Classes/Service/TcaService.php

Currently the palette `yoast-advanced` with the Field `tx_yoastseo_hide_snippet_preview ` is placed in the "Social Media" Tab after the `twitter_image`. Should be moved to the SEO tab.
* Palette `yoast-advanced` moved to SEO tab in page details
* Optimze UX in for the editor
* Apply the TCA change and open die page details in the backend.

Move yoast-advanced palette to SEO tab

---

Configuration/TCA/tx_yoastseo_prominent_word.php

* Add security configuration to ignore page type restrictions for `tx_yoastseo_prominent_word` table.
* Added the `security` configuration in the `ctrl` section with `ignorePageTypeRestriction` set to `true`.
* See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-98487-TCAOptionCtrlsecurityignorePageTypeRestriction.html
Duplicate one or more pages that contain at least one record of `tx_yoastseo_prominent_word`. As long as there is no flash message, respectively sys_log entry, popping up that says: `Attempt to insert record "tx_yoastseo_prominent_word:123" on a page (456) that can't store record type`, the test was successful.
Fixes #602

[TASK] Add security configuration to ignore page type restrictions

---

Classes/Service/LocaleService.php

* If the `interfaceLocale` (backend language) cannot be retrieved, we now fall back to `en_GB` to prevent the translations missing in javascript
* Instead of returning an empty array the `$interfaceLocale` is set to `en_GB`
* Check if the correct language is still taken correctly from your user settings
Fixes #599

[BUGFIX] Fallback to en_GB if no backend locale is found to prevent missing javascript translations
