Yoast/Yoast-SEO-for-TYPO3

Resources/Private/Partials/Description.html
Resources/Private/Templates/Meta.html
composer.json

Added meta description to frontend output

---

.github/CONTRIBUTING.md
README.md

Added basic documentation.

---

Resources/Private/Templates/Module/Edit.html

Fix problem with mixed content.

[TASK] remove hard-coded protocoll for placeholder image #58

---

Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/pages_language_overlay.php

Added renderType in TCA overrides:
https://docs.typo3.org/typo3cms/TCAReference/7.6/Reference/Columns/Select/Index.html#rendertype

#65 added TCA select renderType 'selectSingle' to TCA

---

Resources/Private/Language/da.BackendModule.xlf

Adds translation for Danish for BE

[TASK] Danish translation

---

Classes/Controller/ModuleController.php
Configuration/TCA/Overrides/pages.php
Configuration/TypoScript/setup.txt
Resources/Private/Partials/Title.html
Resources/Private/Templates/Meta.html
ext_tables.sql

[TASK] Added separate field for SEO title

---

Configuration/TypoScript/setup.txt

[BUGFIX] Backend throws: No rendering definition

---

.gitattributes
.gitignore
Classes/Backend/PageLayoutHeader.php
Classes/Controller/ModuleController.php
Configuration/TypoScript/setup.txt
Documentation/Administrator/Index.rst
README.md
Resources/Private/Templates/Module/Edit.html
Resources/Private/Templates/Module/Settings.html
composer.json
ext_localconf.php

- resolves #85 and #87 
- introduces some configuration options kindly sponsored by [ZHdK.ch](https://www.zhdk.ch)

introduce new configuration options

---

Classes/Backend/PageLayoutHeader.php
Classes/Utility/YoastUtility.php
Documentation/Administrator/Index.rst
Tests/Unit/Utility/YoastUtilityTest.php

[FEATURE] Disable snippet preview with PageTs

---

Resources/Public/JavaScript/app.js

Improve notification when something went wrong analysing the content

[FEATURE] Improve notification when something went wrong

---

Classes/Frontend/PageRenderer/PageMetaRenderer.php

[TASK] Cleanup class PageMetaRenderer

---

Classes/Controller/ModuleController.php
Resources/Private/Language/BackendModule.xlf

[TASK] Add language selector in backend module

---

Resources/Private/Language/BackendModule.xlf

[BUGFIX] Add missing backend label for field 'og_image'

---

Documentation/Administrator/Index.rst

Add documentation on how to set fallback images per site root.

Update Administrator Documentation

---

Documentation/Integrator/Index.rst

Update external url to TYPO3 documentation in Integrator documentation.

Update external url in integrator documentation

---

Classes/Form/Element/SnippetPreview.php
Configuration/TCA/Overrides/pages.php
Resources/Private/Templates/TCA/SnippetPreview.html

This prevents errors when creating a page from the context menu.
Resolves: #202

[BUGFIX] Added official fields to save scores to database

---

Classes/UserFunctions/SnippetPreview.php

* Instead of manually call curl, make usage of GeneralUtility::getUrl which uses Guzzle
* Bit of refactoring in the userfunction
* Before calling the Guzzle client, the `$GLOBALS['TYPO3_CONF_VARS']['HTTP']['verify']` has to be set to `false` to accept self signed certificates
* Testing the snippet preview on both http and https environments

[TASK] Use GeneralUtility::getUrl to get the content for snippet-preview

---

Classes/Controller/OverviewController.php
Classes/DataProviders/CornerstoneOverviewDataProvider.php
Classes/DataProviders/PagesWithoutDescriptionOverviewDataProvider.php

Removed CMS9 specific configuration and make it work in CMS8 and 9.
Fixes: #258

[BUGFIX] Make the overview backend module work with CMS8

---

Documentation/Configuration/SnippetPreview/Index.rst

Clarify the storage of configuration for a specific page type

Clarify storage of configuration

---

Classes/UserFunctions/SnippetPreview.php

Restores compatibility with php 7.0
Fixes #266

[BUGFIX] restore compatibility with php 7.0 for TYPO3 8.7

---

Resources/Private/Language/BackendModule.xlf
Resources/Private/Language/BackendModuleDashboard.xlf
Resources/Private/Language/BackendModuleOverview.xlf
Resources/Private/Language/BackendModulePremium.xlf
Resources/Private/Language/BackendModuleSettings.xlf
Resources/Private/Language/BackendModuleUpdate.xlf

Fill the following attributes properly:
- original
- resname
Resolves: #300

[TASK] Follow best practices for XLIFF files

---

.gitattributes

* Ignore additional files/folders on export

[TASK] Ignore additional files/folders on export

---

Classes/Service/PreviewService.php

[TASK] Prevent implode deprecation under PHP 7.4

---

Classes/Service/UrlService.php
Documentation/Configuration/Hooks/Index.rst
Documentation/Configuration/Index.rst

You can now add your own hooks to alter the URLs to analyse. An explanation can be found in the docs. Check the docs by using:
```
ddev docs && ddev launch-docs
```

[FEATURE] Add hook to alter the URL to analyse

---

Classes/Utility/CanonicalizationUtility.php

[BUGFIX] Use the right GET params variable to check params to canonicalize

---

Documentation/Configuration/Permissions/Index.rst

[BUGFIX] Fixed small typo in Documentation

---

Classes/StructuredData/BreadcrumbStructuredDataProvider.php

* While generating an URL within the BreadcrumbStructuredDataProvider, the SiteNotFoundException was not handled. This error could be thrown when you have a site root within a site root where the upper one does not have a site configuration.
* When the exception occurs, an empty URL is returned. The item is only added to the breadcrumb array when the URL is not empty.
* Create a page tree with a siteroot within a siteroot, and only create site configuration for the sub-siteroot. The upper siteroot should not be added to the breadcrumb.

[BUGFIX] Catch SiteNotFoundException within BreadcrumbStructuredDataProvider

---

Classes/Form/Element/SnippetPreview.php

[BUGFIX] Use proper page id for snippet preview on translated records

---

composer.json

* Provide extension key via composer.json
Fixes #416

[TASK] Provide extension key via composer.json

---

Classes/Service/UrlService.php

[BUGFIX] Use rawurldecode to get proper get vars

---

Classes/Utility/YoastUtility.php

Introduced with https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/a9ca2472dcd1ff6b8c4462c0e12ffe41387b86d7

[TASK] Fix CGL issue

---

Classes/StructuredData/BreadcrumbStructuredDataProvider.php

[BUGFIX] Avoid errors with hidden pages and PHP 8

---

Classes/Form/Element/SnippetPreview.php

[BUGFIX] Fix notice exceptions with PHP8

---

Classes/StructuredData/StructuredDataProviderManager.php

[BUGFIX] Use correct call to init pages cache

---

Classes/Form/Element/SnippetPreview.php

Fixes: #574
See linked issue for details.

[BUGFIX] Fix exception with snippet preview when creating a new record
